# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the lineage-17.1 branch
on:
  push:
    branches: [ lineage-17.1 ]
  pull_request:
    branches: [ lineage-17.1 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y eatmydata
          sudo eatmydata apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          sudo eatmydata apt install -y libwxgtk3.0-dev
      
      - name: Prepare environment
        run: |
          mkdir -p ~/bin
          mkdir -p ~/android/lineage
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          source ~/.profile
          
      - name: Prepare environment
        run: |
          source ~/.profile
          cd ~/android/lineage
          repo init -u https://github.com/LineageOS/android.git -b lineage-17.1
          repo sync
